accounts/urls.py
from django.conf.urls import url

from products.views import UserProductHistoryView
from .views import (
    AccountHomeView,
    AccountEmailActivateView,
    UserDetailUpdateView
)

app_name = 'account'

urlpatterns = [
    url(r'^$', AccountHomeView.as_view(), name='home'),
    url(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),
    url(r'history/products/$', UserProductHistoryView.as_view(), name='user-product-history'),
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view(), name='email-activate'),
    url(r'^email/resend-activation/$', AccountEmailActivateView.as_view(), name='resend-activation'),
]

carts/urls.py
from django.conf.urls import url

from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view
)

app_name = 'cart'

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
]

ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

from accounts.views import LoginView, RegisterView, GuestRegisterView
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from carts.views import cart_detail_api_view
from .views import home_page, about_page, contact_page
from billing.views import payment_method_view, payment_method_createview
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView

from carts.views import cart_home

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^account/', include("accounts.urls")),
    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^register/guest/$', GuestRegisterView.as_view(), name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
    url(r'^cart/$', cart_home, name='cart'),
    url(r'^billing/payment-method/$', payment_method_view, name='billing-payment-method'),
    url(r'^billing/payment-method/create/$', payment_method_createview, name='billing-payment-method-endpoint'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^cart/', include("carts.urls")),
    url(r'^orders/', include("orders.urls")),
    url(r'^products/', include("products.urls")),
    url(r'^search/', include("search.urls")),
    url(r'^settings/$', RedirectView.as_view(url='/account')),
    url(r'^settings/email/', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^webhooks/mailchimp/', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from .views import (
    ProductListView,
    ProductDetailSlugView
    )

app_name = 'products'

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail')
]

templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
      integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
<!-- Stripe custom CSS -->
<link rel="stylesheet" href="{% static 'css/stripe-custom-style.css' %}">

templates/base/forms.html
{% extends "base.html" %}


{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <button type='submit' class='btn btn-default'>Save</button>
</form>
</div>
{% endblock %}

templates/base/js.html
{% load static %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

<!-- Django Secure AJAX JS -->
<script src="{% static 'js/csrf.ajax.js' %}"></script>
<!-- eCommerce custom JS -->
<script src="{% static 'js/ecommerce.js' %}"></script>
<!-- eCommerce main JS -->
<script src="{% static 'js/ecommerce.main.js' %}"></script>
<!-- stripe JS -->
<script src="https://js.stripe.com/v3/"></script>
<!-- JS Render-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/1.0.1/jsrender.min.js"></script>
{% include 'base/js_templates.html' %}

templates/base/js_templates.html
    {% verbatim %}
    <script id="stripeTemplate" type="text/x-jsrender">
        <form class="payment-form" action="" method="post" id="payment-form" data-token='{{:publishKey}}'
             data-next-url='{{:nextUrl}}'>
            <div class="form-row">
                <div id="card-element" class="form-control">
                </div>
                <!-- Used to display form errors. -->
                <div id="card-errors" role="alert"></div>
            </div>
            <button class="btn btn-primary my-3 btn-load">{{:btnTitle}}</button>
        </form>
    </script>
    {% endverbatim %}

templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}

{% url 'account:home' as account_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class='container'>
        <a class="navbar-brand" href="{{ home_url }}">
            <img src="//getbootstrap.com/docs/4.1/assets/brand/bootstrap-solid.svg" width="30" height="30"
                 class="d-inline-block align-top" alt="aaa">
            {% if brand_name %} {{ brand_name }} {% else %}eCommerce {% endif %}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == home_url %}active{% endif %}">
                    <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
                    <a class="nav-link" href="{{ contact_url }}">Contact</a>
                </li>
                <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
                    <a class="nav-link" href="{{ product_list_url }}">Products</a>
                </li>


                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Account
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item {% if request.path == account_url %}active{% endif %}" href="{{ account_url }}">Home</a>
                            <a class="dropdown-item" href="{{ account_url }}#billing">Billing</a>
{#          <a class="dropdown-item" href="{% url "account:user-product-history" %}">History</a>#}
{#          <a class='dropdown-item' href='{% url "library" %}'>Library</a>#}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ logout_url }}">Logout</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item {% if request.path == register_url %}active{% endif %}">
                        <a class="nav-link" href="{{ register_url }}">Register</a>
                    </li>
                    <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                        <a class="nav-link" href="{{ login_url }}">Login</a>
                    </li>
                {% endif %}
                <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="nav-link" href="{{ cart_url }}"><span class='navbar-cart-count'>{{ request.session.cart_items }}</span> <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
      </li>

       <!--  <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown link
                    </a>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li> -->

            </ul>
            {% include 'search/snippets/search-form.html' %}
        </div>
    </div>
</nav>